cpanel/elevate

elevate-cpanel
=> Strip service status update from log

elevate-cpanel
=> Add support for digital ocean droplet agent.

elevate-cpanel
=> Preserve imunify license file during elevation

elevate-cpanel
Also reverts #67 as part of resolution.
=> Change service type to simple

elevate-cpanel, t/ea4.t, t/notify.t, t/pecl.t
* Provide a mechanism to add final notifications
* Provide a single final notification for ea4
=> Warn about ea4 dropped packages

elevate-cpanel, t/blockers.t, t/cpanfile, t/ea4.t
Check for EA4 incompatible packages earlier and block if needed
=> Block updates when using incompatible EA4 packages

docs-website-src/content/blockers.md
=> Document the significant known elevation blockers.

elevate-cpanel
=> Authorize elasticsearch.repo

elevate-cpanel
=> Restore colorized logging

elevate-cpanel, t/lib/Test/Elevate.pm, t/outdated_services.t
=> Save blockers to file on --check

elevate-cpanel, t/blockers.t, t/grub2_workaround.t, t/pecl.t, t/stage_file.t
read_stage return the whole stash but most of the
time we need to read one piece of it.
This change teaches 'read_stage' to take an optional argument and return the values for that key.
=> read_stage file can read a specific data

changelog, elevate-cpanel
Fix #135
This is adding the mysql-community.repo to the list of known repos.
=> Add mysql-community.repo to the vetted list

elevate-cpanel, t/ea4.t
Prevent unwanted retention of the created file when the script has no intention of performing the upgrade.
Fixes #126 and CPANEL-41603.
=> Remove backup EA4 profile if run with --check

docs-website-src/content/_index.md, docs-website-src/content/blockers.md, elevate-cpanel
Update doc and fixed a typo in elevate script
=> Update doc for Rocky 8

elevate-cpanel, t/notify.t
=> Do not use ERROR for successfull notifications

elevate-cpanel, t/check-notify.t
=> Fine tune the colors and only use it for the keyword

elevate-cpanel, t/blockers.t
Fix #131
Do not suggest to open a ticket when we know
the MySQL version is not one of the supported ones.
Request the customer to update to the expected version.
=> Better hint for MySQL upgrade

Makefile, elevate-cpanel, t/blockers.t
=> Smoke isolation

elevate-cpanel, t/blockers.t
=> Stop warning about postgresql 9 now CCS supports 10

docs-website-src/content/blockers.md, elevate-cpanel
Increase the disk size for the leapp containers.
=> Increase default disk space

elevate-cpanel, t/ea4.t, t/stage_file.t
Fix #149:
Make sure to purge the previously cached data before replacing them as by default we use a 'merge' method.
=> Cleanup stage_file before storing data

docs-website-src/content/blockers.md
Ref: #176
Add a doc section for the known OVH issue.
We should detect the OVH server and provide a better warning message or blocker.
=> Add a doc notification for OVH monitoring

elevate-cpanel, t/blocker_ovh.t, t/blockers.t, t/cpanel-setup, t/cpanfile
=> Add a warning/blocker for OVH monitoring

LICENSE.md, docs-website-src/content/_index.md, docs-website-src/themes/cptheme/LICENSE, docs/blockers/index.html, docs/categories/index.html, docs/index.html, docs/tags/index.html, docs/whitepaper/index.html, elevate-cpanel
=> Bump copyright

elevate-cpanel, t/check_and_fix_grub.t
https://github.com/cpanel/elevate/issues/190
=> Check and fix grub for net.ifnames=0

elevate-cpanel, t/blockers_check_yum_repos.t
See second commit in set for "the bug I found along the way."
Internal tracking/testing notes can be found in BC-6268.
=> Fix #151 and another bug I found along the way

elevate-cpanel
=> Typo fixup

elevate-cpanel
As expected, my XXX comment (which gets removed here) proved prophetic RE bugs upon encountering testing.
=> Updates after testing revealed better reponames for imunify

docs-website-src/config.toml, docs-website-src/content/_index.md, docs-website-src/themes/cptheme/layouts/partials/left_menu.html
First commit in set is the actual change, second just commits what hugo generated for it.
Internal case for tracking BC-6465 also contains notes about where to go to view these changes in a browser (I slapped it up onto a colo server)
=> Update support/issue links, remove experimental language

elevate-cpanel, lib/Elevate/Components/cPanelPlugins.pm, script/elevate-cpanel.PL
That component was badly named, and is in charge
of restoring cpanel plugins / packages.
=> Rename ArchRPMs component to cPanelPlugins

elevate-cpanel, lib/Elevate/Blockers/Grub2.pm, lib/Elevate/Blockers/Repositories.pm
Pretty sure I got em all this time, nothing left that looks relevant anymore per git grep
=> Replace last remaining instances of issues reference with cPSupport

elevate-cpanel, lib/Elevate/Blockers/BootKernel.pm, lib/Elevate/Blockers/WHM.pm, t/blocker-whm.t
Transient license issues may cause problems for the upgrade. Do a best-effort check to figure out if their license is okay, right this moment and block if that fails.
=> Block on license issue

elevate-cpanel, lib/Elevate/Motd.pm
=> Fix MOTD message being blank due to fatpacker stripping it out

elevate-cpanel, lib/Elevate/Service.pm
=> Be defensive around local in --service mode by forcing it in svc file

elevate-cpanel, lib/Elevate/Blockers.pm, lib/Elevate/Blockers/AbsoluteSymlinks.pm, lib/Elevate/Components/AbsoluteSymlinks.pm, script/elevate-cpanel.PL, t/components-AbsoluteSymlink.t
Took more time than I thought because I was busy getting frustrated trying to test till I gave up on it
=> Add logic to fix absolute symlinks in / and notice about us doing this

lib/Elevate/Blockers.pm
=> if we run check-upgrade to a specific flavor, suggest to run the correct command

elevate-cpanel, lib/Elevate/Blockers.pm
=> Fix bad getopt caller, that is delegated to cpev

docs-website-src/content/blockers.md, docs-website-src/themes/cptheme/layouts/partials/left_menu.html, elevate-cpanel, lib/Elevate/Blockers.pm
Also fixes a bad link to `#faq` anchor on one page
=> Add some more documentation fixes, this time around NIC blocker

elevate-cpanel, lib/Elevate/Logger.pm
Would have added tests, but this is a component with none. Simple enough change regardless, just followed Foy's reccomendations about this sort of thing online from 2011.
=> Set UTF-8 flag in log4perl config, should fix #277

docs-website-src/content/_index.md
=> Add FAQ when stuck on stage 1

.github/workflows/website.yml
=> Regenerate website on push to docs

elevate-cpanel, lib/Elevate/Blockers/Repositories.pm
=> Add 'EA4-c$releasever' to vetted list

elevate-cpanel, lib/Elevate/Components/MySQL.pm
=> Mysql cover

docs-website-src/content/_index.md, elevate-cpanel, lib/Elevate/Blockers.pm, lib/Elevate/Blockers/AbsoluteSymlinks.pm, lib/Elevate/Blockers/Base.pm, lib/Elevate/Blockers/BootKernel.pm, lib/Elevate/Blockers/Databases.pm, lib/Elevate/Blockers/Grub2.pm, lib/Elevate/Blockers/IsContainer.pm, lib/Elevate/Blockers/NICs.pm, lib/Elevate/Blockers/Python.pm, lib/Elevate/Components/AbsoluteSymlinks.pm, lib/Elevate/Components/Base.pm, lib/Elevate/Components/EA4.pm, lib/Elevate/Components/RmMod.pm, lib/Elevate/Components/RpmDB.pm, lib/Elevate/Motd.pm, lib/Elevate/Usage.pm, script/elevate-cpanel.PL, t/blocker-IsContainer.t, t/leapp_upgrade.t
=> Add --no-leapp option to pause the process

elevate-cpanel, script/elevate-cpanel.PL
Cases BC-6603 and BC-6604: Ensure that the powertools and epel repos are enabled, and disable cpanel-plugins repo during upgrade.
=> Enable powertools and epel repos, and disable cpanel-plugins repo.

elevate-cpanel, lib/Elevate/Blockers/Repositories.pm
=> Enable support for vzzo repo “ct-preset”

elevate-cpanel, lib/Elevate/Blockers/Base.pm, lib/Elevate/Blockers/Repositories.pm, t/blocker-Repositories.t
=> Include JSON data about repo in blocker reporting.

elevate-cpanel, script/elevate-cpanel.PL
Fix #318
If the LEAPP_OVL_SIZE is set capture the value
at startup and honor it later.
=> Allow user to customize LEAPP_OVL_SIZE

elevate-cpanel, lib/Elevate/Blockers.pm, script/elevate-cpanel.PL
=> Refuse to run if --check has not first been run successfully

elevate-cpanel, lib/Elevate/Blockers.pm
=> Fix conjugation of to be verb in blocker message

changelog, elevate-cpanel, script/elevate-cpanel.PL
=> Fix typo in help docs. s/convertion/conversion/

elevate-cpanel, script/elevate-cpanel.PL, t/cpanfile, t/pod.t
Case RE-77: This also fixes a POD error in elevate-cpanel due to a missing newline.
Changelog:
=> Assure all submitted code has valid POD.

elevate-cpanel, lib/Elevate/Blockers/WHM.pm, t/blocker-whm.t
=> Provide expected version when cPanel version is not up to date.

docs-website-src/content/_index.md
=> Document possible statuses in /var/cpanel/elevate

elevate-cpanel, lib/Elevate/Blockers/Base.pm, lib/Elevate/Blockers/Repositories.pm, t/blocker-Repositories.t, t/blocker-Repositories_system_update_check.t
=> Re 89 fixups

elevate-cpanel, t/Elevate-Database.t, t/blocker-Databases.t
Case RE-153:  Update unit tests for the changes made for this user
story.
Changelog:
=> Update unit tests

elevate-cpanel, lib/Elevate/Components/RpmDB.pm, script/elevate-cpanel.PL
=> Do not run /usr/bin/rm to remove a single file

elevate-cpanel, script/elevate-cpanel.PL, t/blocker-ea4.t
=> Fix typo: compoment

elevate-cpanel, script/elevate-cpanel.PL
RE-295:
Changelog: Fix help typo - "major version of"
=> Fix help typo - major version of

elevate-cpanel, script/elevate-cpanel.PL
=> Grammar fixes to --help documentation

docs-website-src/content/blockers.md
Case RE-167:
Audit all the blocker modules and update the blocker documentation to accuratly reflect the issues for which we  block.
Changelog: Updated the documentation about the blockers.
=> Update blocker documentation

elevate-cpanel, lib/Elevate/Blockers/EA4.pm, lib/Elevate/EA4.pm, t/blocker-ea4.t, t/components-ea4.t
Case RE-313:  Update unit tests to assert that the script meets the expected behavior
Changelog:
=> Add unit tests for RE-313

docs-website-src/content/blockers.md
Case DOC-20349:  This change fixes up the requests from documentation for case RE-134.
Changelog:
=> Update blocker documentation for filesystem

docs-website-src/content/blockers.md
=> Update blocker documentation for changes in RE-338, RE-34, and RE-337

maint/generate_changelog
=> Fix encoding handling in changelog generator

elevate-cpanel, lib/Elevate/Components/ELS.pm, lib/Elevate/OS.pm, lib/Elevate/OS/CentOS7.pm, lib/Elevate/OS/RHEL.pm, script/elevate-cpanel.PL
Case RE-368:
Use the manual method to remove ELS. This involves deleting two files and un-installing the package.
Changelog: Removes ELS for CentOS 7.
=> Remove ELS for CentOS 7

elevate-cpanel, lib/Elevate/Blockers/Distros.pm, lib/Elevate/OS/CloudLinux7.pm, t/blocker-Distros.t
Case RE-500:  Remove support for CloudLinux
Changelog:
=> Remove support for CloudLinux

elevate-cpanel, lib/Elevate/Blockers/Grub2.pm, lib/Elevate/Blockers/Repositories.pm, t/blocker-Repositories.t
Add some simple verbiage in that shows in all cases given `yum makecache` is non-zero.
=> Case RE-361: Make it more clear why yum makecache failures are a problem

elevate-cpanel, lib/Elevate/OS/CentOS7.pm
case RE-534: Thankfully is just a simple regexp to catch all these.
=> Account for ELS rollout repos as well

Makefile
- Should now work on any OpenStack image of a cPanel install after v110.
- Now uses cpm for module dependency installs.
- All Path hardcoding has been removed and replaced with Globals where appropriate.
=> RE-639: Fix makefile paths.

.github/workflows/openstack.yml, .github/workflows/openstack/reboot_watch.sh, .github/workflows/openstack/ssh_retry.sh, .github/workflows/openstack/status_marker.sh, .github/workflows/openstack/terraform/cloud-config.yaml, .github/workflows/openstack/terraform/cloud-init.yml, .github/workflows/openstack/terraform/main.tf, .github/workflows/openstack/terraform/outputs.tf, .github/workflows/openstack/terraform/variables.tf, t/integration/complete.t
=> Local Re 618

Makefile, t/03_fatpack-script.t, t/cpanel-setup, t/cpanfile
Case RE-857: Add test to enforce that the script has been fatpacked
Changelog:
=> Add test to enforce that the script has been fatpacked

.github/workflows/pruner.yml
=> Fix path in openstack pruner.

elevate-cpanel, lib/Elevate/OS/RHEL.pm
Case RE-845: Add the `ul` repo and any repo that starts with `ul_` to the list of vetted repositories.
Changelog: Add 'ul' and 'ul_*' to the list of vetted repositories.
=> Add UnifiedLayer repos to vetted list

.github/workflows/openstack/prune_openstack, .github/workflows/pruner.yml
=> Small fixes to pruner.

elevate-cpanel, lib/Elevate/Components/RpmDB.pm, lib/Elevate/OS/RHEL.pm
Case RE-844:
Add the hbdedi repo to the list of vetted repos and automatically remove two obsolete packages installed from that repo:  eigid and quickinstall.
Changelog: Add support for the hgdedi repo.
=> Add support for the hgdedi repo

.github/workflows/openstack/prune_openstack
Case RE-924: Get github pruner for elevate-cpanel working
Changelog:
=> Get github pruner for elevate-cpanel working

.github/workflows/openstack.yml, .github/workflows/openstack/ssh_retry
- Appleboy updated to latest version
- reboot sleep lowered to be more aggressive.
=> RE-937: Fix race condition that can occur between ssh_retry and reboot_watc

t/components-Softaculous.t
Case RE-942: Complete the unfinished unit testing for the Softaculous component added as part of RE-846.
Changelog:
=> Complete unit tests for Softaculous component

docs-website-src/content/blockers.md, elevate-cpanel, lib/Elevate/Components/Repositories.pm
case RE-158: Hopefully this reduces the amount of issue filings on that. Phrasing reviewed by Katherine Frain in DOCS-261.
=> Add some notes in the blocker FAQ about unsupported repos

elevate-cpanel, lib/Elevate/Roles/Run.pm, t/ssystem.t
Changelog: Fail with a more specific error about what executable is not available
=> Document what executable is failing

t/integration/complete.t
case RE-948: I did the best here to be terse but understandable, which was difficult without the QA tools. Regardless, I think this will work.
=> Beef up integration test

t/integration/complete.t
The 'imunify360' service does not report that it is running even if it is up and running so we are skipping this service check for now.
Changelog:
=> Skip checking the imunify360 service in the integration test

.github/workflows/openstack/prune_openstack, .github/workflows/pruner.yml
- Bumped appleboy actions to latest version
- Pruner now PERL
=> RE-950: Convert BASH pruner to PERL

elevate-cpanel, lib/Elevate/Components/JetBackup.pm, lib/Elevate/OS/Ubuntu20.pm, lib/Elevate/PkgMgr/APT.pm, t/components-ElevateScript.t, t/components-JetBackup.t, t/usage.t
Fix t/usage.t when noc_reccomendations file exists as well Fix bizzare errors in t/ test for ElevateScript that failed due to local configuration when running the testsuite during development.
=> Remove blocker for JetBackup on Ubuntu

elevate-cpanel, lib/Elevate/Components.pm, lib/Elevate/Components/Grub2ChecksWorkarounds.pm, lib/Elevate/Components/Grub2ControlTest.pm, lib/Elevate/OS.pm, lib/Elevate/OS/RHEL.pm, lib/Elevate/OS/Ubuntu.pm, script/elevate-cpanel.PL, t/check_and_fix_grub.t, t/components-Grub2ChecksWorkarounds.t, t/components-Grub2ChecksWorkarounds_parse_shell_variable.t, t/components-Grub2ControlTest.t, t/grub2_workaround.t
=> Add Ubuntu support for bootloader test

.github/workflows/openstack-centos-7.yml, .github/workflows/openstack-ubuntu-20.yml, .github/workflows/openstack/reboot_watch, .github/workflows/openstack/ubuntu-20.04/cloud-config.yaml, .github/workflows/openstack/ubuntu-20.04/cloud-init.yml, .github/workflows/openstack/ubuntu-20.04/main.tf, .github/workflows/openstack/ubuntu-20.04/outputs.tf, .github/workflows/openstack/ubuntu-20.04/variables.tf, t/integration/ubuntu20-to-ubuntu22/complete.t
Case RE-1027: Add the u20->u22 openstack workflow
Changelog:
=> RE-1027:Add the u20->u22 openstack workflow

.github/workflows/openstack-centos-7.yml, .github/workflows/openstack-cloudlinux-7.yml, .github/workflows/openstack/centos-7/main.tf, .github/workflows/openstack/centos-7/variables.tf, .github/workflows/openstack/cloudlinux-7/main.tf, .github/workflows/openstack/cloudlinux-7/variables.tf, .github/workflows/openstack/prune_openstack, .github/workflows/testsuite.yml
Reorganize workflows so that they are all dependent on the same testsuite passing
Case RE-1026: Testsuit.yml as parent to OpenStack workflows.
Changelog:
=> Case RE-1026: Testsuit.yml as parent to OpenStack workflows.

.github/workflows/openstack-ubuntu-20.yml, .github/workflows/openstack/ubuntu-20.04/cloud-config.yaml, .github/workflows/openstack/ubuntu-20.04/cloud-init.yml, .github/workflows/openstack/ubuntu-20.04/main.tf, .github/workflows/openstack/ubuntu-20.04/outputs.tf, .github/workflows/openstack/ubuntu-20.04/variables.tf, .github/workflows/testsuite.yml, t/integration/ubuntu20-to-ubuntu22/complete.t
Case RE-1027: Add the u20->u22 openstack workflow
Changelog:
=> Add the u20->u22 openstack workflow

docs-website-src/config.toml, docs-website-src/content/_index.md, docs-website-src/content/blockers.md, docs-website-src/content/elevate-faq.md, docs-website-src/content/getting-started.md
Case DOCS-315: Initial restructure of docs to separate them logically. A  few language updates added.
=> WIP Initial restructure of elevate docs

docs-website-src/config.toml
Case DOCS-315: Trying to fix sidebar
=> Hopefully fixing sidebar

docs-website-src/content/_index.md, docs-website-src/content/blockers.md, docs-website-src/content/elevate-faq.md, docs-website-src/content/getting-started.md, docs-website-src/themes/cptheme/layouts/partials/left_menu.html
=> Fixup minor bugs in docs website

docs-website-src/config.toml, docs-website-src/content/_index.md, docs-website-src/content/blockers.md, docs-website-src/content/elevate-faq.md, docs-website-src/content/getting-started.md
Case DOCS-315: Some more updates and cleanup with the ELevate docs.
=> More ELevate docs tweaks
