elevate-cpanel
t/ea4.t

When using some unsupported package the
ea_current_to_profile script is going to
add noise to the STDOUT... we need to improve
the output parsing logic to be able to get
a json file.

Improve ea_current_to_profile output parser

---

elevate-cpanel
t/blockers.t

Allow the elevate-cpanel script to notify the administrator if a newer
version of the script is available. Also allow the admin to skip this
blocker if desired.
Implements #25.

Check for whether the running script is updated

---

elevate-cpanel

Originally, logging to a file was done by piping screen output to
`tee(1)`. This prevented some output from being logged, as only the
systemd service did this. Instead, use a native log4perl file appender
to log to the file.
This eliminates colored output, since there is no direct way to save
color data to the file anymore. Restoring this feature will be explored
in a future issue.
Resolves #71 and #83.

Handle log output with log4perl

---

elevate-cpanel

Currently, MySQL repositories are being removed during stage 2, but
MySQL packages are being removed in stage 3 prior to invoking leapp.
This is likely to be causing problems. Instead, defer disabing the repos
until after the packages have been removed.
Fixes #66.

Move disabling of MySQL repos after removing packages

---

elevate-cpanel

Nested definition of `$out` in `reinstall_mysql_packages` is causing
that function to report less useful information in the case of a MySQL
upgrade failure. Report the more useful final status of the upgrade,
rather than the initial return value of the API call which kicked off
the process.
Fixes #75.

Fix reporting of final MySQL upgrade status

---

elevate-cpanel

Only log to file when elevate-cpanel is passed `--service` argument.
Fixes #88.

Turn off screen appender when run as service

---

elevate-cpanel

It was decided that labelling whether output lines came from stdandard
out or standard error for commands run through `ssystem` is not worth
the additional noise. Remove these labels from the log output.
Fixes #89.

Remove output stream labels from ssystem()

---

elevate-cpanel
t/elevate-marker.t

Change the timestamps recorded for the start and end markers in the
stage file, to ease the process of analyzing data about conversions.
Implements #91.

Use BigQuery timestamps for start/end markers

---

elevate-cpanel
t/blockers_check_yum_repos.t

So that additional information can be made available, allow blockers to
add additional keys other than `id` and `msg` for eventual use by
external programs, and use this to collect the list of yum repositories
with installed packages not yet known to work.
Implements #107.

Allow augmenting blocker objects

---

docs-website-src/content/blockers.md
elevate-cpanel
t/blockers.t

By default, the upgrade process has been converting normal GRUB2 boot
loader entries into files compatible with a subset of the Boot Loader
Specification. (A [Fedora wiki entry
<https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault>](https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault)
describes the details.) However, server providers may boot into a
version of GRUB2 which does not understand BLS or does not properly
parse these files. If this happens, the upgrade process will cause the
system to no longer boot without manual intervention.
BLS is (currently) optional for AlmaLinux 8, and it is possible to
suppress this conversion by explicitly setting `GRUB_ENABLE_BLSCFG` to
`false` in `/etc/default/grub` prior to the upgrade. Therefore, block
upgrades if this is not …

Block if BLS is not disabled in /etc/default/grub

---

elevate-cpanel
t/blockers.t
t/blockers_parse_shell_variable.t
t/lib/Test/Elevate.pm

QA reported that #112 was unable to handle double-quoted values, which
it should, because `/etc/default/grub` and similar files are able to be
any valid shell variable assignments, including non-constant expressions.
Since there is no better parser of shell scripts than the shell, use
that to extract the value from the file. Drop UID to `nobody` and run
`bash` in its restricted mode to try to prevent unintended side effects.
Since direct I/O isn't used anymore, switch the tests of the blocker
itself to use Test::MockFile, and write a test for the shell-based
parsing mechanism. This requires rewriting a few of the previous tests.
By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: …

Re-work the BLS blocker

---

elevate-cpanel

Check `Cpanel::OS::distro()` against `centos` rather than `Centos`.
Fixes #114.

Fix typo in distro detection fallback

---

elevate-cpanel
t/blockers.t
t/blockers_parse_shell_variable.t
t/grub2_workaround.t
t/lib/Test/Elevate.pm

At least one server provider of note boots their default Linux images using a version of GRUB2 which looks for its configuration, boot entries, and modules at `/boot/grub`, which is the Debian convention; however, the RHEL convention is to install GRUB2 things into `/boot/grub2`. In images for older distros (such as CentOS 7), they had been working around this by creating a symlink at `/boot/grub/grub.cfg` which points to `/boot/grub2/grub.cfg`, which allows booting when the boot entries are in native GRUB2 configuration. However, in newer distros, they have changed this workaround to symlink the entirety of `/boot/grub` to point to `/boot/grub2`. The reason for this is that BLS is implemented through the use of a GRUB2 module, and the symlink of only the configuration file neglects to …

Address BLS by detecting and updating provider workarounds for GRUB2 prefix

---

changelog
elevate-cpanel
t/blockers.t
t/blockers_check_yum_repos.t
t/disk_space.t
t/ea4.t
t/grub2_workaround.t
t/leapp_upgrade.t
t/lib/Test/Elevate.pm
t/notify.t
t/outdated_services.t

Add a new option '--upgrade-to' to select which distro to upgrade to. By default elevate to AlmaLinux 8.
Rocky 8 upgrade are now supported.
Perform an upgrade:
/scripts/elevate-cpanel --start --upgrade-to=rocky
Check blockers:
/scripts/elevate-cpanel --check --upgrade-to=rocky

Elevate to AlmaLinux or Rocky 8

---

elevate-cpanel
t/ea4.t

Add an helper 'is_check_mode' to know if we are
currently running with '--check' or not.
Previously we were checking '! _abort_on_first_blocker' attribute to know if check mode was enabled.

Backup EA profile to a temporary file on --check

---

changelog
elevate-cpanel

For testing purposes, allow overriding the base URL for version checking and updates without modifying the script. Additionally, fix a bug in the update process that prevents the script from properly detecting that it is up to date.

Allow alternate update URL

---

elevate-cpanel
t/blockers.t

cPanel version 110 will no longer allow upgrading from MariaDB 10.2 to 10.3, regardless of current OS. Thus, in this case, recommend upgrading to 10.5 instead.

Recommend proper MariaDB version for cPanel v110

---

elevate-cpanel
t/blocker_system_update_check.t
t/blockers.t
t/ssystem.t

Fix #130
Adjust the '_system_update_check' to do not block
when only kernel updates are required from:
yum check-update
If any other packages than a 'kernel*' is detected then this is still a blocker and we request the use to then run 'yum update' as before.

Do not block when detecting kernel update required

---

docs-website-src/config.toml
docs-website-src/content/_index.md
docs-website-src/themes/cptheme/layouts/partials/left_menu.html
elevate-cpanel

Add 'FAQ' and 'SumUp' sections to the website.
Enforce sanity check for stage 2,3 and 4.
If the leapp process failed we end up in Stage 4
without being on a AlmaLinux 8 yet... thus reset
the stage to 3 to avoid being locked.
Reversely we cannot run stage 2 or 3 while being
on major version 8.

Sanity check before/after leapp process

---

elevate-cpanel

If the file `/var/cpanel/elevate-noc-recommendations` exists, present the user with a generic warning asking them to check with their server provider. If the file has contents, display those instead of the generic warning. Prompt for an acknowledgement that the user has done what has been requested, and bail out if this is not answered in the positive.
Implements #198.

Check for warning file from server provider

---

elevate-cpanel

Currently, several warnings, including "your chance now to cancel the update process", take place within stage 1 proper. As such, by the time a user decides to cancel at the last moment, they are already committed to the upgrade. Because the dialog implemented in #201 also occurs right before this warning, replying in the negative also traps the user into the upgrade process.
The call chain used to arrive at the old location for the code is:
run_stage_1 <- _run_service <- run_service_and_notify <- start
The only other way the flow of execution converges on the same path to reach stage 1 is where the handler for `--service` invokes `run_service_and_notify` directly. Since that isn't an interactive process, there is no merit to presenting these warnings under those circumstances, which …

Move the last chance warnings to before stage 1

---

elevate-cpanel

The EasyApache packages for the development files belonging to the OpenSSL builds used on CentOS 7 do not depend on the main packages being present. As such, it is possible for the `ea-openssl-devel` package to have become an orphan when `ea-openssl` was replaced with `ea-openssl11`.
Since the absence of these development packages do not cause problems for cPanel itself, allow the script to ignore the removal of these packages, at least for the purpose of the EA4 compatibility blocker.
Fixes #119.

Exempt EA4 OpenSSL devel packages from blocker

---

elevate-cpanel
t/check_and_fix_grub.t

Kernels installed after ELevate has upgraded the system do not hard-code their command line arguments into the individual bootloader entry but instead refer to a variable in GRUB's persistent environment, stored in `/boot/grub2/grubenv`. Although a full `grub2-mkconfig` does appear to update the `kernelopts` GRUB environment variable from `GRUB_CMDLINE_LINUX` in the contents of `/etc/default/grub`, the only time this is run when a kernel is installed, it specifically excludes environment variable updates. The only other thing that explicitly touches the GRUB environment is to change the `saved_entry` variable to update the default boot option.
Since a full `grub2-mkconfig` is overkill just to update the environment, use the `grub2-editenv` utility to update the appropriate variable.
By …

Also update the kernel command line arguments in the GRUB environment file

---

elevate-cpanel
t/elevate-marker.t

Create the `elevate_version_start` and `elevate_version_finish` keys in the stage file, recording the version of elevate-cpanel at the same time as the starting and ending timestamps and OS versions.
Implements #202.
Additionally, fix a minor bug when elevate-cpanel detects no XS-based RPM-sourced Perl modules to reinstall.

Record version in stage file

---

lib/Elevate/Components/PerlXS.pm

Ran into this issue with several servers where `$self->cpev` is undefined in `lib/Elevate/Components/Base.pm`
This causes #243 
To resolve this we can just call `restore_perl_xs` in the same way `purge_perl_xs` is called.
Then `cpev` will be defined on `$self` and prevent the error:
```
Can't call method "can" on an undefined value at /usr/local/cpanel/scripts/elevate-cpanel line 1787.
```
I am not super familiar with perl so please let me know if this is not possible due to some other reason.

Passing self to restore_perl_xs for use with ssystem call - Fixes #243

---

elevate-cpanel
script/elevate-cpanel.PL

In this case, $self already was an argument to the subroutine, so the replacement was rather straightforward.

Fix more bad ssystem calls

---

docs-website-src/content/blockers.md
elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/Blockers/BootKernel.pm
script/elevate-cpanel.PL

The leapp framework requires the ability to instruct the boot loader to load the OS with a custom initrd. If this is not possible, the upgrade will not work. However, since we cannot directly determine whether we can affect the boot loader without rebooting[*], use kernel versions as a proxy.
[*] It is possible to guarantee agency over the boot loader by adding a dummy kernel parameter, which could be detected after reboot with `/proc/cmdline`; however, this method was considered to be overkill.

Block if the running and boot kernels differ

---

docs-website-src/content/_index.md

It was determined that the "Before Updating" section of the Documentation page does not adequately describe what is meant by "console access" or "back up". Elaborate on these topics.

Clarify the "Before Updating" section of the docs

---

elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/Blockers/Python.pm
lib/Elevate/Blockers/Repositories.pm
script/elevate-cpanel.PL
t/blocker-Python.t

Also fix explosion due to bad caller of Base in InvalidYumRepo check
A part of me says "a real shame we gotta do this" as it appears? `python3` is installed by default on c7. That said, only place where this could harm things is if for some reason a customer has cpanel-yarn/cpanel-node/etc. packages which are all generally development packages and not something customers would have installed (as they, oddly enough, depend on python3).

Add blocker for python36 and test

---

elevate-cpanel
lib/Elevate/Blockers/Base.pm
lib/Elevate/Components/Base.pm

Refs: #264
Improve the error message when trying to call a missing function or when cpev object is undefined so we can understand and fix the error.

Improved error message when calling missing functions

---

elevate-cpanel
lib/Elevate/Blockers/WHM.pm
lib/Elevate/Constants.pm
t/blocker-whm.t

For now I still tolerate the older versions, as there's no reason to break this. Still, if we're telling folks to upgrade, we may as well tell them to go to the last one we're gonna support for c7.

Impose maximum LTS version, change version recommendation to v110

---

elevate-cpanel
script/elevate-cpanel.PL

Should fix false positive failures we've been seeing, it cleared it up for me

Clear Cpanel::OS' $instance cache because it's definitely wrong on rocky

---

elevate-cpanel
script/elevate-cpanel.PL

The notifications already get printed before exiting in the success case of `run_service_and_notify`, which incidentally is right before stage 5 finishes and then additionally prints the final_notifications.

Remove duped final_notifications display on GreatSuccess

---

elevate-cpanel
lib/Elevate/Blockers.pm
script/elevate-cpanel.PL

See notes on internal case for more details. Suffice to say, the logic for doing the symlink just was never being ran due to the argument to _has_blockers previously always being '1' (check only... don't write out things we need to do later to /var/cpanel/elevate).
Should fix issues on Linode, did for me in testing

Pass through the "check only" mode status properly to fix #274

---

elevate-cpanel
script/elevate-cpanel.PL
t/cpanfile

~~(Note: This PR will not pass the tests until CPANEL-42903 is backported to an acceptable cPanel release.)~~
Work with an existing leapp answerfile while still ensuring that the pam_pkcs11 removal is acknowledged. Use the answerfile directly, rather than touching the userchoices, as leapp only intends users to modify the answerfile.
Fixes #216.

Use leapp answerfile instead of userchoices file

---

lib/Elevate/Blockers/Repositories.pm

The officially recommended repo file for ElasticSearch uses `elasticsearch` as the YUM repo ID; however, a third-party document seems to use `elasticsearch-7.x` for whatever reason. The contents of the file are more or less equivalent.

Vet elasticsearch-7.x repoid

---

elevate-cpanel
lib/Elevate/SystemctlService.pm

When the service is not installed, we still try to blindly stop and disable the service.
This was raising confusing error messages.
This change is adding a protection to the stop and disable functions to abort earlier when not needed.

Improve stop and disable function from Systemctl

---

elevate-cpanel
lib/Elevate/Blockers/BootKernel.pm

Fix #305
Note, the 'Cpanel::Exception::get_string' can return either a yaml or json formatted string. This is hard to predict depending on the stack/version.
The '_to_str' helper is taking both into account.

Fixup BootKernel error message

---

elevate-cpanel
script/elevate-cpanel.PL
t/leapp_upgrade.t

Previously, the check used by blockers to determine if the script will run leapp was incompatible with the check option as it only read a file that was written just prior to running stage 1.  This updates the check to see if we should run leapp to also check to see if the --no-leapp option was passed via CLI in order to make the sub compatible with the check option.
Fixes #332

Teach should_run_leapp to check for the CLI option

---

.github/workflows/testsuite.yml
changelog
elevate-cpanel
lib/Elevate/Constants.pm
script/elevate-cpanel.PL
t/cpanel-setup

This is the last version to support c7, so we want to fix this script to only run on this version.  This will minimize testing and risk moving forward.
Fixes #337

Add blocker if cPanel is not running version 110

---

docs-website-src/content/_index.md

Fixes #334. Updated the documentation to state that one must run --check to check for blockers before running --start to start the migration.

Document that running --check is required before migration

---

changelog
elevate-cpanel
lib/Elevate/Blockers.pm
script/elevate-cpanel.PL

Fixes #348. When running start, first perform a full check for blockers, display them all to the user,
and do not start the migration if any are found.

Incorporate running --check into running --start

---

docs-website-src/content/blockers.md
elevate-cpanel
lib/Elevate/Blockers/Databases.pm
t/blocker-Databases.t

This patch is requested by cPanel Support to try to prevent users of PostgreSQL on cPanel from being surprised that their databases are unavailable once the ELevate process completes; see CPANEL-43203 for previous discussion.
----
Modify the Databases blocker to add a condition which checks for the following three conditions:
1. a `postgresql-server` package is installed;
2. the file `/var/cpanel/acknowledge_postgresql_for_elevate` does not exist;
3. one or more cPanel users have a PostgreSQL database mapped to them.
If all three are true, issue a blocker. In the blocker message, indicate which cPanel accounts have relevant databases, point the admin to resources which explain how to update the PostgreSQL data directory, and instruct the admin on how to acknowledge the blocking warning …

Block when cP accts have DBs on distro PgSQL

---

changelog
elevate-cpanel
lib/Elevate/Blockers/EA4.pm
t/blocker-ea4.t

Case RE-93:  The EA4 blocker check would return after backing up the EA4 profile.  This early return occurred every time since the logic backing up the EA4 profile returned undef which resulted in a non-functional EA4 blocker check.  This change removes the early return which allows the EA4 blocker check to complete.
Fixes #253

Do not return from EA4 blocker check prematurely

---

script/elevate-cpanel.PL
t/blocker-DiskSpace.t
t/blocker-Python.t
t/blocker-Repositories.t
t/components-AbsoluteSymlink.t
t/cpanfile
t/tidy.t

Add tidy check to the test suite

---

elevate-cpanel
script/elevate-cpanel.PL

Case RE-94
Changelog: Get fix-cpanel-perl to run after distro change without breaking perl.

Break X::Tiny not perl to force fix-cpanel-perl to run

---

elevate-cpanel
lib/Elevate/Components/JetBackup.pm

Case RE-103: Their versioning scheme changed so reinstall would do the
incorrect thing. We now need to do yum update jetbackup not reinstall.
Changelog: Update elevate for jetbackup to be aware of JetBackup 5.3

Update elevate for jetbackup to be aware of JetBackup 5.3

---

elevate-cpanel
script/elevate-cpanel.PL

Case RE-56:
Fixes #347. Invoking the script with --check (or --start) will run a more thorough and informative version check as well as checking for any other issues of concern.
Changelog: Removed the simple version check from the BEGIN
block of the script since this happens during the check
operation.

Remove cPanel version check in the BEGIN block

---

elevate-cpanel
lib/Elevate/Usage.pm
t/usage.t

RE-57: Inform user of invalid/ineffective command
line option combinations to reduce potential confusion.
Changelog: Improved command line option validation

Improve command line option validation

---

elevate-cpanel
lib/Elevate/Components/Base.pm
lib/Elevate/Components/EA4.pm
lib/Elevate/RPM.pm
lib/Elevate/Service.pm
lib/Elevate/SystemctlService.pm
script/elevate-cpanel.PL
t/components-ea4.t

Case RE-38: Previously, we did restore any custom configuration files for packages provided by EA4.  This could lead to things like the PHP memory_limit being reset to default and custom modsec rules no longer being applied after the server was elevated.  This change restores custom configuration files for packages provided by the EA4 repo so that customizations will stick after the server has been elevated.
Changelog: Restore config files for packages provided by the EA4 repo

Restore config files for packages provided by the EA4 repo

---

elevate-cpanel
script/elevate-cpanel.PL

Case RE-2: Previously, if you ran the ELevate script, got to step 5, and went to your server after the reboot, you could potentially not be informed that ELevate was still running. This commit fixes it so the MOTD will not be updated until the script is complete.
Changelog: Always show ELevate MOTD when ELevate is running.

Always show ELevate is in progress when it is.

---

elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/Blockers/SSH.pm
lib/Elevate/Components/SSH.pm
script/elevate-cpanel.PL
t/blocker-SSH.t
t/components-SSH.t

Case RE-112: For sshd, the default value for PermitRootLogin changes from "yes" to "no" when upgrading from CentOS 7 to a CentOS 8 variant. We used to block if PermitRootLogin was not explicitly set; but, instead it is more desirable to simply emit a warning that we are going to set it to "yes" and go ahead and set it so the behavior stays the same post upgrade. I've altered the SSH blocker module to emit the warning and not block. I've also moved the SSH blocker execution to happen earlier so the warning is more visible.  And, I've added a component that will provide the autofix for the sshd configuration file.
Changelog: Set PermitRootLogin for sshd to 'yes' if not explicitly
set in the configuration file so that the behavior does not
change after the upgrade.
By submitting pull …

Convert ssh blocker to an autofix

---

elevate-cpanel
script/elevate-cpanel.PL

Case RE-186: This flag is mentioned in the help text for the script and there are examples using it, but the flag is not explicitely documented. This change documents the flag.
Changelog: Document manual-reboots flag in help text

Document manual-reboots flag in help text

---

elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/Blockers/Base.pm
lib/Elevate/Blockers/CloudLinux.pm
lib/Elevate/OS.pm
lib/Elevate/OS/CloudLinux7.pm
lib/Elevate/OS/RHEL.pm
script/elevate-cpanel.PL
t/blocker-CloudLinux.t

Case RE-173:  CloudLinux's fork of ELevate verifies that the CloudLinux licese is valid and inhibits the elevation process from starting if it is not.  Due to this, we need to block if the CloudLinux license is not valid in order to avoid leaving the system in a broken state.
Additionally, I fixed a bug where the argument would not be numeric in exit when blockers were set to abort on the first blocker, and a bug where the blocker was not added before dying in this same situation which would result in the elevate-blockers file essentially being null.
Changelog: Add blocker for invalid CloudLinux licenses

Add blocker for invalid CloudLinux licenses

---

elevate-cpanel
lib/Elevate/Blockers/Databases.pm
t/blocker-Databases.t

Case RE-188:
Instead of, rather inefficiently, invoking uapi for each user, get the users with postgres databases from the dbindex.db.json file. This will quickly get that list of users regardless of the status of the postgres feature.
Changelog: Improve the check for PostgreSQL users to be more
efficient and to not throw errors if the feature is disabled
for any of the users.

Fix PostgreSQL user database check when feature disabled

---

elevate-cpanel
lib/Elevate/Blockers/Databases.pm
lib/Elevate/Blockers/Leapp.pm
lib/Elevate/Components/MySQL.pm
lib/Elevate/Database.pm
lib/Elevate/OS.pm
lib/Elevate/OS/CloudLinux7.pm
lib/Elevate/OS/RHEL.pm
script/elevate-cpanel.PL

Case RE-153: This change detects if CL MySQL or cPanel MySQL is in use.
If cPanel MySQL is in use, then use the previous logic to handle MySQL.
If CL MySQL is in use, then block if MySQL is below version 5.5.
Otherwise, allow the elevate process to continue, and allow leapp to
handle updating MySQL for CL8 as leapp should handle it.
Changelog: Add support for CL MySQL

Add support for CL MySQL

---

elevate-cpanel
lib/Elevate/Blockers/Grub2.pm
t/blocker-Grub2.t

Case RE-83:
Changelog: Block if the grub2-pc package is not installed
or if the grub.cfg file is missing.

Block if grub not installed or config file missing

---

elevate-cpanel
lib/Elevate/Blockers/Distros.pm
lib/Elevate/OS.pm

Case RE-249: Elevate did not detect the correct OS on a server that had been elevated and still had the staging file in place.  This was due to the cached OS value still being present in the staging file.  Due to this, elevate did not bail out as expected on an OS that was not eligible to be elevated.
Changelog: Ensure proper OS detection on servers that have been
previously elevated

Have bail_out_on_inappropriate_distro() remove Elevate::OS cache

---

elevate-cpanel
lib/Elevate/Components/UnconvertedModules.pm
script/elevate-cpanel.PL
t/components-UnconvertedModules.t

Case RE-213: Previously, there was logic that would remove known modules that do not convert to el8 in run_stage_4().  This change moves that logic from being executed directly in run_stage_4() to a new post_leapp component.  It also splits this logic into two separate parts:
1.  It removes the packages that were installed for leapp as those packages are no longer necessary after the conversion.
2.  It detects any other packages that are el7 packages and warns about them since they were developed for RHEL 7 based OSs.
Changelog: Convert logic to remove modules that do not convert into
component

Convert logic to remove modules that do not convert into component

---

elevate-cpanel
lib/Elevate/Blockers/Leapp.pm
lib/Elevate/Leapp.pm
lib/Elevate/Roles/Run.pm
t/leapp_upgrade.t

Case RE-223:
Normally, during a leapp upgrade or preupgrade, leapp reports any issue when inhibits an upgrade in the
leapp-report.json file and flags it as in "inhibitor". Sometimes, however, leapp encounters a fatal error which is not flagged as such in the report file.
Fatal errors will show up in the stdout in a special "ERRORS" block. Also, if leapp encounters either an inhibitor or any other fatal error, the exit code will be non-zero.
So, if we have a non-zero error code, and an error block reported in leapp's stdout, we should report this as a blocker.

Also block on the 'leapp preupgrade' ERRORS

---

elevate-cpanel
script/elevate-cpanel.PL

Case RE-138: This commit makes it so scripts/upcp and bin/backup are removed early in stage 2 so cron or another entity cannot run them during the ELevate process.
Changelog: Ensure upcp and backups cannot run at the same time
as ELevate.

Ensure upcp and backups cannot run at the same time as ELevate.

---

elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/Blockers/AutoSSL.pm
lib/Elevate/Components/AutoSSL.pm
script/elevate-cpanel.PL
t/blocker-AutoSSL.t
t/components-AutoSSL.t

Case RE-54:
When CentOS 7 is elevated to AlmaLinux 8, the "nobody" user will retain its uid/gid of 99 where as on AlmaLinux 8 the expected uid/gid for "nobody" is 65534. This will cause issues with the Sectigo AutoSSL provider.
If a system is setup to use Sectigo as the AutoSSL provider, emit a warning that the system will be switched to Lets Encrypt. Run the appropriate autofixer for the conversion during the upgrade
Changelog: Change to Let's Encrypt if Sectigo is the AutoSSL provider.

Convert systems using Sectigo to use Let's Encrypt

---

elevate-cpanel
lib/Elevate/OS.pm
script/elevate-cpanel.PL
t/Elevate-Database.t
t/blocker-Python.t
t/lib/Test/Elevate.pm

Case RE-265: The start option had an order of operations issue where it would attempt to parse the upgrade_to option before validating that it could start / was not already running.  Since parsing the upgrade_to option validates that the distro is appropriate, it would clear the Elevate::OS cache which could result in the script dying once leapp finished elevating.  This change ensures that the validation that the script can start occurs before parsing the upgrade_to option.
Changelog: Validate script can execute start option before parsing
upgrade_to option

Validate script can execute start option before parsing upgrade_to

---

elevate-cpanel
script/elevate-cpanel.PL

Case RE-274: The warning string in the last chance message was hard coded to CentOS 7.  Since we now support multiple OSs, this string needs to be updated to be a variable showing the proper OS that is being updated.
Changelog:  Update string in last chance message to inform the user of
the correct OS that is being updated

Update warning string in last chance message

---

elevate-cpanel
lib/Elevate/Roles/Run.pm
t/ssystem.t

Case RE-260: C::S::O has a bug in 110 where it does not detect missing scripts (see CPANEL-40343).  The change in CPANEL-40343 was deemed medium/high risk, and was rejected as a backport candidate for 110.  As such, we need to work around this issue.  Since elevate-cpanel can only be executed as root, it was determined that all commands that it executes should be executabl absolute paths.  This change enforces that.
Changelog:  Ensure all system calls are executable absolute paths

Ensure all system calls are executable absolute paths

---

elevate-cpanel
lib/Elevate/Blockers/Base.pm
lib/Elevate/Blockers/Databases.pm
lib/Elevate/Components/DatabaseUpgrade.pm
lib/Elevate/Database.pm
script/elevate-cpanel.PL
t/Elevate-Database.t
t/blocker-Databases.t

Case RE-171:
Instead of simply having a blocker for old versions of MySQL/MariaDB, give the option to auto-upgrade
during the elevate process. Also, give them the option to specify which version to which they prefer to upgrade. We can only do this when MySQL/MariaDB is provided by cPanel, not CloudLinux.
Changelog: Provide auto-upgrade mechanism for out-of-date
MySQL/MariaDB versions (installed via cPanel, not CloudLinux).

Handle auto-upgrade of out-of-date MySQL installs

---

elevate-cpanel
lib/Elevate/Leapp.pm
script/elevate-cpanel.PL
t/leapp_upgrade.t

Case RE-224: This commit adds in some extra checks to help determine if the LEAPP process failed or not. It also introduces a new potential touch file at /var/cpanel/elevate_leap_fail_continue that can be used to continue even if the new checks detect a possible error.
Changelog: Added in more checks to report potential failures of
LEAPP.

Report potential failures of LEAPP.

---

elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/Blockers/Base.pm
lib/Elevate/Components/Base.pm
lib/Elevate/Components/UnconvertedModules.pm
lib/Elevate/OS.pm
lib/Elevate/OS/CentOS7.pm
lib/Elevate/OS/CloudLinux7.pm
lib/Elevate/OS/RHEL.pm
lib/Elevate/Usage.pm
script/elevate-cpanel.PL
t/blocker-Databases.t
t/usage.t

Case RE-218: Upstream leapp support for Rocky Linux is considered beta / best effort.  As such, we have decided to no longer support elevating to Rocky Linux.
Changelog: Remove support for elevating to Rocky Linux

Remove support for elevating to Rocky Linux

---

docs-website-src/content/_index.md
docs-website-src/content/blockers.md

Case RE-218:  Since we no longer support Rocky Linux or the 'upgrade-to' option, we need to remove references to both of them in our documentation.  This change updates the documentation to remove references to both Rocky Linux and the upgrade-to option.
Changelog:

Update docs to remove references to Rocky Linux

---

elevate-cpanel
lib/Elevate/Blockers/Leapp.pm

Case RE-261:
When an unknown blockage happens, a generic message is provided to the user. We wish to to provide a more meaningful message to help the user find more information to why they were blocked. The files under'/var/log/leapp' will sometimes contain more detailed information about leapp preupgrade blockers.
Changelog: In the event of a blocker found by performing
a leapp preupgrade, direct the user to the /var/log/leapp
directory to find more information.

Provide more information with leapp preuprade blockers

---

docs-website-src/content/_index.md
docs-website-src/content/blockers.md

Case RE-144:  In case RE-18, we added support for CloudLinux 7 to CloudLinux 8 upgrades.  At the time, this was deemed experimental, so we held off on updating our documentation to reflect this.  However, in version 33 of this script, the experimental tag for CloudLinux was removed.  As such, we now need to update the documentation to reflect that CloudLinux is supported.
Changelog:

Update documentation to reflect that CloudLinux upgrades are supported

---

elevate-cpanel
lib/Elevate/Blockers/DNS.pm
t/blocker-dns.t

Case RE-318:  Updated to check name server type the system is using in order to determine whether to block on it.
Changelog: Fix DNS blocker to check the systems name server type.

Fix DNS name server blocker

---

elevate-cpanel
lib/Elevate/Leapp.pm
script/elevate-cpanel.PL
t/leapp_upgrade.t

Case RE-305: Also restructured _wait_for_log_contents to handle corner cases for a better flow

Do not delay 10 minutes when elevate_leap_fail_continue is put in place

---

lib/Elevate/Blockers/EA4.pm

Case RE-313:  Currently, the EA4 blocker will block if there are any packages that will be dropped (not provided on the newer OS) during the elevation.  This change teaches the blocker to check to see if any domains are using the installed version of PHP.  If there are no domains using the version of PHP that will be dropped, then we no longer block for that version of PHP and allow the elevation to continue if that was the only thing blocking it.
Changelog:

Do not block on dropped PHP packages if no domains use them

---

elevate-cpanel
lib/Elevate/Blockers/WHM.pm
lib/Elevate/Components/CCS.pm
script/elevate-cpanel.PL
t/blocker-whm.t
t/components-CCS.t

Case RE-78: This change converts the CCS blocker to a component.
* Remove the CCS blocker
* Export the CCS data to a secure directory prior to starting leapp
* Remove the CCS package prior to starting leapp
* Remove some cruft that the CCS package leaves behind prior to leapp
* Install the CCS package after leapp completes
* Import the CCS data after leapp completes
Changelog: Convert CCS blocker to component

Convert CCS blocker to component

---

docs-website-src/content/_index.md
docs-website-src/content/blockers.md

Case RE-78:  This code in this case converts the CCS blocker to a component.  This change updates the documentation to remove an unsupported software section from the blockers documentation page since the only thing that the unsupported software section contains is that CCS is unsupported.  Since CCS is now supported, we might as well remove the entire section from the page.
Changelog:

Remove unsupported software section from blockers documentation

---

script/elevate-cpanel.PL

Case RE-313:  Imunify needs to be restored before EA4 post_leapp to ensure that hardened PHP versions remain in place if they are installed. This changes the ordering of the post_leapp components so that Imunify is restored before EA4.
Changelog:

Restore Imunify before EA4 post_leapp

---

elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/Blockers/MountPoints.pm
script/elevate-cpanel.PL
t/blocker-MountPoints.t

Case RE-306:  The 'leapp' utility needs to be able to load packages stored within the
'/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/files/bundled-rpms' directory.  If '/usr' is a separate private bind mount, the 'leapp' utility will be unable to load the packages stored within this directory which will result in 'leapp' failing, and leaving systems in a broken state.  In order to avoid this, we now detect this scenario and block the elevation.
Changelog: Add blocker if '/usr' is a separaate private mount point

Add blocker if '/usr' is a separate private mount point

---

lib/Elevate/Blockers/EA4.pm
lib/Elevate/Components/EA4.pm

Case RE-313: Imunify 360 is a paid product that provides hardened PHP versions that are available on newer OS versions.  Currently, the EA4 blocker would block on older PHP versions such as ea-php54 since they are EOL and not provided on AlmaLinux 8 by cPanel.  However, Imunify 360 provides these versions of PHP on AlmaLlinux 8 as well as 7 so elevate should not block if the hardened PHP version is provided by Imunify 360. This change updates the EA4 blocker to no longer block on hardened PHP versions that are provided by Imunify 360.
Changelog:

Teach EA4 blocker about hardened PHP provided by Imunify 360

---

docs-website-src/content/blockers.md
elevate-cpanel
lib/Elevate/Blockers/Grub2.pm
lib/Elevate/Blockers/MountPoints.pm
t/blocker-MountPoints.t

Case RE-134: Since the script reboots the server and relies on the file system to be consistent between reboots, we need to ensure that mount -a exits cleanly before starting the elevate process.  This change adds a blocker to the script is mount -a fails to exit cleanly.
Changelog: Have script block if mount -a fails to exit cleanly

Have script block if mount -a fails to exit cleanly

---

docs-website-src/content/blockers.md

Case RE-313:  The EA4 blocker now detects if dropped PHP versions are in use and allows the elevation to proceed if they are not in use.  It also detects if the dropped PHP versions are provided by Imunify 360's hardened PHP repo as they are not dropped in this specific use case. This change updates are blocker docs to reflect this.
Changelog:

Update blocker documentation to reflect EA4 blocker changes

---

elevate-cpanel
lib/Elevate/Blockers/EA4.pm
lib/Elevate/Components/Base.pm
lib/Elevate/Components/EA4.pm
lib/Elevate/EA4.pm
script/elevate-cpanel.PL
t/blocker-ea4.t
t/components-ea4.t

Case RE-313:  Currently, the EA4 blocker is biggest road blocks for our customers to being able to elevate their servers to A8/CL8.  This change enhances the EA4 blocker to no longer block on installed versions of PHP that are not provided by A8/CL8 unless there are domains actively using the installed version of PHP.  It also teaches the EA4 blocker about hardened PHP versions that are provided by the Imunify 360 plugin since these versions of PHP would are available on A8.  Additionally, it refactors some logic that is shared between the EA4 blocker and EA4 component into a shared library (Elevate::EA4).
Changelog:  Enhance EA4 blocker so that it only blocks on installed PHP
versions that are not provided by Imunify 360 and are actively in use by
domains on the server
By submitting pull …

Enhance EA4 blocker

---

elevate-cpanel
lib/Elevate/Blockers/EA4.pm
lib/Elevate/Components/EA4.pm
t/blocker-ea4.t
t/components-ea4.t

Case RE-358:  If the version of PHP being installed is provided by Imunify 360 post elevate, it is possible that any domains using it will be reset to use the inherited version of PHP instead.  Since this can break the website for those domains, we need to ensure that they are set to the correct version of PHP after elevate completes.
Changelog:

Restore PHP vhost versions post elevate

---

elevate-cpanel
lib/Elevate/Blockers/EA4.pm
t/blocker-ea4.t

Case RE-362: When Imunify 360 is installed, it is possible to install the ea-profiles-cloudlinux package which is provided by Imunify 360 and available on C7 and A8.  Previously, the EA4 blocker would consider ea-profiles-cloudlinux a dropped package and block based on it being installed.  This change teaches the blocker to check to see if this package is provided by Imunify 360 and allows it the elevation to continue if it is.  It also adds this package to the list of packages provided by Imunify 360 that need to be reinstalled after the elevation completes if it is installed and provided by Imunify 360.
Changelog:

Teach EA4 blocker about ea-profiles-cloudlinux provided by Imunify 360

---

elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/Blockers/Imunify.pm
script/elevate-cpanel.PL
t/blocker-Imunify.t

Case RE-373: If a server has an invalid Imunify license, then the Imunify component can fail in expected ways.  This can further lead to the elevate script failing in stage 4 due to the Imunify post_leapp component failing and the EA4 component relying on the Imunify component to succeed.
Changelog: Add blocker for an invalid Imunify license

Add blocker for an invalid Imunify license

---

elevate-cpanel
lib/Elevate/Components/RpmDB.pm

Case RE-132:  The leapp utility will remove some packages due to incompatibility/dependency related issues after the upgrade to AlmaLinux/CloudLinux 8 has been completed.  Rather than relying on leapp to handle the removal of these packages (potential upstream bugs), we should instead manually remove them as part of a pre_leapp component. This change updates a component to perform this removal prior to leapp executing.
Changelog:  Have pre_leapp component remove packages that leapp will
remove

Have pre_leapp component remove packages that leapp will remove

---

.gitignore

Just a small modification to gitignore to also ignore VSCode workspace files in addition to the `.vscode` folder.

Ignore *.code-workspace file in .gitignore

---

elevate-cpanel
lib/Elevate/Blockers/Repositories.pm
t/blocker-Repositories.t

Case RE-343:
During the test of yum's stability, try running "yum clean all" and retry running "yum makecache" if it fails on the first try. Hopefully this will prevent blockers.
Changelog: Runs "yum clean all" and retries "yum makecache" if it
had initially failed.

Attempt "yum clean all" if "yum makecache" fails

---

elevate-cpanel
lib/Elevate/Blockers/Repositories.pm
t/blocker-Repositories.t

Case RE-338:
But, when performing the upgrade, go ahead and clean up the unfinished yum transactions.
Changelog: No longer blocks if there are unfinished yum transactions.

No longer block on unfinished yum transactions

---

maint/generate_changelog

Case RE-447:  It was determined that we no longer want to rely on build-tools/generate_changelog in order to generate the changelog for a new version of elevate.  This change makes it so that elevate's generate_changelog script parses the git logs directly rather than relying on wrapping 'build-tools/generate_changelog' in order to perform this task.
Changelog:

Update generate_changelog to no longer rely on build-tools

---

elevate-cpanel
lib/Elevate/Leapp.pm
t/leapp_upgrade.t

Case RE-475:  In case RE-224, we added a check to ensure that leapp has completed before continuing with stage 4 / starting the post leapp components.  Unfortunately, this check did not account for the no-leapp option that the script provides for those who want to perform the upgrade from C7->C8 without using the leapp utility, but still want the script to handle the cPanel specific potions of the upgrade.  This resulted in upgrades using the no-leapp option to fail in stage 4 while waiting on leapp to complete.  This change teaches this check about the no-leapp option which allows for upgrades using this option to skip past this check.
Changelog: Teach wait_for_leapp_completion() about the no-leapp option
By submitting pull requests to this repo, I agree to the Contributor License …

Teach wait_for_leapp_completion() about the no-leapp option

---

elevate-cpanel
lib/Elevate/Blockers/Leapp.pm
lib/Elevate/Blockers/NICs.pm
lib/Elevate/Components/NICs.pm
lib/Elevate/Constants.pm
lib/Elevate/NICs.pm
script/elevate-cpanel.PL
t/blocker-NICs.t
t/components-NICs.t
t/elevate-nics.t

Case RE-337:  Previously, we blocked if we found that there were multiple NICs with names conflicting with the kernel naming space.  This change makes it so that we give a warning about this when the script is executed in check mode, and we rename the NICs to a different naming scheme if the script is executed in start mode.  Of note, we do explicitely ask the user for permission to make this change on their behalf before performing the change since there is an inherint risk involved of networking not coming back up when the server reboots.
Changelog: Convert multiple NICs blocker to component

Convert multiple NICs blocker to a component

---

elevate-cpanel
script/elevate-cpanel.PL

Case RE-450: Ensure the environment is setup for the default POSIX locale before elevating.
Changelog: Set locale environment variables to “C” before elevating.

Set locale environment variables to “C” in BEGIN block

---

elevate-cpanel
lib/Elevate/Blockers/EA4.pm
lib/Elevate/Components/EA4.pm
lib/Elevate/EA4.pm
t/blocker-ea4.t
t/components-ea4.t

Case RE-403:  In RE-313, we added support for Imunify 360's hardened PHP repo to the EA4 blocker.  Unfortunately, this improvement did not account for some packages that Imunify 360's hardened PHP repo does not provide which has resulted in some servers making it past the EA4 blocker that had packages installed that were not supported on A8/CL8. This change removes the current logic to support Imunify 360's hardened PHP repo, and replaces it by teaching
'Elevate::EA4::_backup_ea4_profile' to use the 'CloudLinux_8' target when Imunify 360 is installed with the hardened PHP feature.  We can do this since Imunify 360's hardened PHP feature is essentially just providing CloudLinux's EA4 to servers with the feature available.
Changelog: Use 'CloudLinux_8' target to backup EA4 profile on …

Use 'CloudLinux_8' target to backup EA4 profile with I360 installed

---

t/cpanel-setup

CentOS 7 went EOL on June 30th, and the mirrors were removed within a few hours of it going EOL.  As such, we need to update the repo file to point to vault before doing anything with yum in the setup script.
Changelog:

Update cpanel-setup to set base repo to use vault

---

elevate-cpanel
lib/Elevate/Blockers.pm
lib/Elevate/OS.pm
script/elevate-cpanel.PL

Case RE-505:  Previously, a user or security advisor could execute --check in the middle of a failed elevation.  It does not make sense for this to be allowed since the elevation attempt has already made it past the blocker stage.  At this point, it is far more appropriate for the user to execute --continue in order to complete the elevation.
Of note, one of the side affects of this is that --check will clear the Elevate::OS cache which will cause failures if the elevation attempt has already made it to stage 4 or 5 and the OS has been upgraded, but cPanel services and friends have not been restored.
Changelog:  Do not allow check to run in the middle of an elevation
By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: …

Do not allow check to run in the middle of an elevation

---

Makefile
elevate-cpanel
lib/Elevate/Roles/Run.pm

Give better context when `ssystem_and_die` blows up as requested.
Additionally, update the tags file generation target in the Makefile to handle the now-modular nature of the project.

Use croak() instead of die() in ssystem_and_die

---

elevate-cpanel
lib/Elevate/Blockers/Base.pm
lib/Elevate/Blockers/Repositories.pm
lib/Elevate/YUM.pm
t/blocker-Repositories.t

Case RE-420:  Previously, we ignored packages that were installed directly via the RPM binary or packages that were installed from repositories that had since been disabled.  This led to elevations being allowed to continue when they should have been blocked due to packages being installed from unvetted sources.  This could lead to services or other things being broken on the server after the elevation has completed.  This change makes it so that we detect when packages are installed from disabled repositories and when packages are installed directly via the RPM binary.
Changelog:  Block when packages are installed from a disabled repo
By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: …

Block when packages are installed from a disabled repo

---

elevate-cpanel
lib/Elevate/OS/RHEL.pm

Case RE-542: In RE-420, we updated the Repository blocker to check for packages installed from repositories that are no longer enabled.  This resulted in jetapps support being broken since the jetapps repositories were not in the list of vetted repositories.  This change reinstates jetapps support.
Changelog:  Add jetapps-* to the list of vetted repos

Add jetapps-* to the list of vetted repos

---

elevate-cpanel
lib/Elevate/Components/ELS.pm

Case RE-538:  Previously, we would check to see if the 'els-define' package was installed and return early in this pre_leapp component. However, due to the CentOS 7 base repo moving to vault, it was found that ELS was installed while yum was in a broken state which resulted in the 'els-define' package not getting installed.  As such, this change makes it so that we always remove the ELS repo files if they exist since we can not rely on the 'els-define' package being installed.
Changelog: Have ELS component always remove the ELS repo files if they
exist

Have ELS component always remove the ELS repo files if they exist

---

elevate-cpanel
lib/Elevate/Blockers/Repositories.pm
t/blocker-Repositories.t

Case RE-452: leapp has an inhibitor in place to check for any repositories that duplicate repo IDs.  This can lead to a situation where --check recommends that a server is ready for elevation, and --start blocks since it 'leapp preupgrade' is only executed during --start.  This change adds a blocker to perform the same check the leapp performs so that we can block and advise the customer how to remove the blocker during --check.  Additionally, one of the things that is triggering this issue on customer server appears to be repo files that are put in place by the product during MariaDB upgrades.  As such, this change also adds in an autofix if the duplicate repo ID matches MariaDBXX since it was likely put in place by the product and will be removed as part of the pre_leapp component for …

Add blocker for duplicate repo IDs

---

elevate-cpanel
lib/Elevate/Components/PECL.pm
script/elevate-cpanel.PL
t/pecl.t

case RE-72: Also updates pecl.t, should pick up a bit more cover
Changelog: Update PECL check to run before EA in pre_leapp phase; use
php_get_installed_versions to determine EA PHP package versions.

Update PECL checks

---

elevate-cpanel
lib/Elevate/Blockers/Imunify.pm
t/blocker-Imunify.t

Case RE-404: The output of the Imunify license check could be really noisy in the output while in check mode making it more difficult to pick out if a blocker has been found.  This change makes it so that the output of this command is no longer printed to STDOUT or logged.
Changelog: Do not log output of Imunify license check

Do not log output of Imunify license check

---

elevate-cpanel
lib/Elevate/Components/Base.pm
lib/Elevate/Components/R1Soft.pm
lib/Elevate/Constants.pm
lib/Elevate/OS/RHEL.pm
lib/Elevate/YUM.pm
script/elevate-cpanel.PL
t/components-R1Soft.t

Case RE-502:
In cases where the R1Soft backup agent is installed, we need uninstall it.  Then after the the OS upgrade, reinstall kernel-devel, then reinstall the backup
agent.
Changelog: Enable elevate on systems with the R1Soft
Backup Agent installed.

Create new component to handle R1Soft agent

---

elevate-cpanel
lib/Elevate/Components/MySQL.pm

Case RE-544: When MySQL governor takes over the MySQL install, it can leave a mix of packages from the MariaDB/MySQL upstream and MySQL/MariaDB CloudLinux repos in place.  After discussing this with CloudLinux's developers, it was determined that CloudLinux's version of leapp is able to handle this situation and that elevate should NOT remove these packages as it result in a situation where the database is NOT installed.  This change makes it so that elevate does NOT remove any database packages if it determines that the database server is provided by CloudLinux.
Changelog: Do not cleanup database packages if the database is provided
by CloudLinux
By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: …

Do not cleanup database packages if the database is provided by CL

---

elevate-cpanel
lib/Elevate/Components/WPToolkit.pm

Apparently this is no longer required.
Changelog: Stop using the --noscripts flag when erasing wp-toolkit-cpanel
in pre-leapp stage.

RE-113: Stop using the --noscripts flag to rpm -e on wp-toolkit-cpanel

---

elevate-cpanel
lib/Elevate/Components/Grub2.pm
lib/Elevate/Notify.pm
lib/Elevate/Roles/Run.pm
script/elevate-cpanel.PL
t/components-Grub2.t
t/lib/Test/Elevate.pm

Case RE-514: Currently, the script assumes that leapp will have sufficient control over the boot process via GRUB2 configuration. This can result in upgrades making it all the way to leapp only to discover that leapp cannot boot into the custom environment leapp uses to carry out the upgrade, leading to a system that largely cannot be restored into a fully functional state.
It is possible to check that changes made to the bootloader are reflected in the behavior of the boot process, but this requires doing work prior to any major changes to the system. Stage 1 is an ideal time for this, but also stage 1 was not designed to result in a reboot, unlike every other stage. To make this work, the bootstraping of the elevate-cpanel service has been moved to a pre-stage, and the start and …

Check whether leapp can control the boot process

---

elevate-cpanel
lib/Elevate/EA4.pm

Case RE-535: A server with Imunify 360 installed could report that it had the hardened PHP feature, but either have the repo disabled or not have updated the ea-cpanel-tools package to be provided by CloudLinux. This would result in the EA4 blocker check failing because it would attempt give the EA4 backup script
(/usr/local/bin/ea_current_to_profile) the 'CloudLinux_8' target which the cPanel version of ea-cpanel-tools does not provide.  This would result in the command failing due to an invalid target.  This change makes it so that we verify that ea-cpanel-tools is being provided by CloudLinux before assuming that Imunify 360 provides hardened PHP.
Changelog: Have check that Imunify 360 provides hardened PHP ensure that
the 'ea-cpanel-tools' package is provided by the CloudLinux …

Have Imunify 360 check ensure ea-cpanel-tools is provided by CL

---

elevate-cpanel
lib/Elevate/Components/EA4.pm
lib/Elevate/RPM.pm
t/components-ea4.t

Case RE-499: The restore logic for EA4 config files was broken when the packages were provided by either CloudLinux's EA4 repo or Imunify's hardened PHP repo.  This was because the restore logic was gathering the EA4 packages based on the repoid that they came from, but the regex only took cPanel's version of EA4 into account.  This change makes it so that we gather these packages based on the package prefix of 'ea-' so that the config files for the installed packages are always gathered regardless of which repo provides them.
Fixes #486
Changelog: Fix restore logic for config files of packages provided by
EA4

Restore EA4 config files based on package prefix

---

elevate-cpanel
lib/Elevate/Blockers/Leapp.pm

Case RE-614: Upstream leapp version 0.19.0 is currently in testing but pending being released to stable sometime this month.  One of the changes in this version is the name of the inhibitor that checks the loaded kernel modules.  It changes from 'check_installed_devel_kernels' in version 0.16.0 to 'check_detected_devices_and_drivers' in version 0.19.0.  In order to ensure elevate-cpanel supports both versions of upstream leapp, we simply add 'check_detected_devices_and_drivers' to the list of inhibitors to ignore so that it is ignored under both names.
Changelog: Add 'check_detected_devices_and_drivers' to list of
inhibitors to ignore in the leapp preupgrade check to prepare for
upstream leapp version 0.19.0
By submitting pull requests to this repo, I agree to the Contributor License …

Add 'check_detected_devices_and_drivers' to list of inhibitors to ignore

---

elevate-cpanel
lib/Elevate/Blockers/Databases.pm
lib/Elevate/Components/DatabaseUpgrade.pm
script/elevate-cpanel.PL
t/blocker-Databases.t
t/components-DatabaseUpgrade.t

See commits in this PR for more detailed explanation as to what I fixed versus the original submission by @sfbee 

RE-34: Unblock the Elevate Blocker when remote MySQL is enabled by disabling remote Mysql during upgrade

---

elevate-cpanel
lib/Elevate/Blockers/EA4.pm
lib/Elevate/Components/EA4.pm
lib/Elevate/EA4.pm
script/elevate-cpanel.PL
t/blocker-ea4.t

Case RE-611: With the changes to the logic to support Imunify 360 on CentOS 7, it was found that sites using older hardened PHP versions no longer had the correct version of PHP set after elevate completed.  This was because the changes to the Imunify 360 logic made it so that the code path that gathered and stored this information was no longer reachable.  As such, this logic has been refactored to only check for PHP versions that would otherwise be dropped after the upgrade to AlmaLinux 8 that are not in use and the logic to gather and store the current PHP usage has been moved to the EA4 component so that it always gets executed and thus the logic to set the PHP version after the elevation will always get executed now too.
Changelog: Move logic to gather and store php usage to a …

Move logic to gather and store php usage to a component

---

elevate-cpanel
lib/Elevate/Components/MySQL.pm
lib/Elevate/Database.pm

Case RE-543: The contents of my.cnf have the potential to cause the restoration of the database server to fail.  As such, we need to restore the original my.cnf from pre_leapp after restoring the database server in post_leapp.  Once the custom my.cnf is restored, we should attempt to restart the database service to make sure that it starts with the original my.cnf from before elevate began in place.  If it does, then we can move on.  If it does not, then we need to put the default my.cnf that is generated by the installation process of the database restore back in place and make sure that the database service starts with it in place.  This change makes it so that it is more likely for the database service to be installed and running after post_leapp component for it has completed.
Fixes …

Restore my.cnf after installing the database server during post_leapp

---

elevate-cpanel
lib/Elevate/Components/MySQL.pm

Case RE-662
Changelog: Fix text in failure advice when MySQL restore fails

Fix text in failure advice when MySQL restore fails

---

elevate-cpanel
lib/Elevate/Components/Panopta.pm
lib/Elevate/OS/RHEL.pm
script/elevate-cpanel.PL

Case RE-43:
If they have the Panopta agent installed, simply remove it since it is deprecated and will be incompatible with Elevate. Do not block if the FortiMonitor repo is present.
Changelog: No longer block on Panopta or FortiMonitor

Do not block on Panopta or FortiMonitor

---

elevate-cpanel
lib/Elevate/Components/Repositories.pm
lib/Elevate/OS.pm
lib/Elevate/OS/CloudLinux7.pm
lib/Elevate/OS/RHEL.pm

Case RE-247: Leapp natively handles the update of the EPEL repository, so our handling of EPEL is superfluous. Remove it.
Changelog: Permit leapp to handle updates to the EPEL repository.

Remove our handling of EPEL in favor of leapp's

---

.github/workflows/openstack.yml
.github/workflows/openstack/reboot_watch.sh
.github/workflows/openstack/ssh_retry.sh
.github/workflows/openstack/status_marker.sh
.github/workflows/openstack/terraform/cloud-config.yaml
.github/workflows/openstack/terraform/cloud-init.yml
.github/workflows/openstack/terraform/main.tf
.github/workflows/openstack/terraform/outputs.tf
.github/workflows/openstack/terraform/variables.tf
t/integration/complete.t

- Uses Github Actions and Terraform to create a centos-7 instance running the latest 11.110.0.* build.
- Checks out the source PR branch.
- Copies Elevate from source PR branch into /scripts/elevate-cpanel.
- Updates cPanel License.
- Runs elevate-cpanel.
- Tracks each reboot and cycles through them
- Upon completion of elevate-cpanel prove is run against t/integration/* where only complete.t currently resides and can be heavily expanded with additional tests.
- Upon successful pipeline - the OpenStack instance is destroyed.
- Upon failed pipeline - the OpenStack instance is kept alive for investigation.

RE-618: Automate C7->A8 happy path regression test on PR creation

---

elevate-cpanel
lib/Elevate/Components/PackageRestore.pm
lib/Elevate/RPM.pm
script/elevate-cpanel.PL
t/components-PackageRestore.t

Case RE-574:
During elevate net-snmp will get uninstalled when mysql-libs gets uninstalled. On AlmaLinux 8, net-snmp does not depend on mysql-libs so we can reinstall it after the upgrade.
Changelog: Ensure that system with net-snmp installed will have it
installed post-elevate.

Restore net-snmp if it had been installed prior to elevate

---

elevate-cpanel
lib/Elevate/Leapp.pm

Case RE-217: The _report_leapp_failure_and_die sub does less than the search_report_file_for_inhibitors sub for no good reason. Use the latter in the former, rather than re-implementing parsing of the report file.
Changelog: Re-work Leapp failure handling to report all inhibitors.

Rework Elevate::Leapp to reuse code

---

docs-website-src/content/_index.md
elevate-cpanel
lib/Elevate/Blockers/Base.pm
lib/Elevate/Blockers/BootKernel.pm
lib/Elevate/Blockers/Grub2.pm
lib/Elevate/Blockers/IsContainer.pm
lib/Elevate/Blockers/Leapp.pm
lib/Elevate/Blockers/NICs.pm
lib/Elevate/Components/Base.pm
lib/Elevate/Components/Grub2.pm
lib/Elevate/Leapp.pm
lib/Elevate/Usage.pm
script/elevate-cpanel.PL
t/components-Grub2.t
t/leapp_upgrade.t
t/usage.t

Case RE-695: Don't assume that leapp will be the only distro upgrade process we will be wrapping.
Changelog: Turn `--no-leapp` into a more generic
`--upgrade-distro-manually` option, but continue to recognize
`--no-leapp` as an alias for it.

Genericize `--no-leapp`, et al.

---

elevate-cpanel
lib/Elevate/Blockers/Repositories.pm
lib/Elevate/YUM.pm

Case RE-603: In RE-420, we started blocking on packages that do not have an associated repo.  This led to a significant spike in the number of servers that were eligible to be elevated out of the box.  Upon looking at the data returned from the blocker added via RE-420, we found that there were several packages that we could whitelist for this blocker which would reduce the number of servers that were blocked out of the box.  This change creates the whitelist and ignores the packages that were added in it.
Changelog: Add a whitelist for some legacy pacakges without a repo

Add a whitelist for some legacy packages without a repo

---

elevate-cpanel
lib/Elevate/Blockers/Base.pm
lib/Elevate/Blockers/DNS.pm
lib/Elevate/Blockers/Databases.pm
lib/Elevate/Blockers/DiskSpace.pm
lib/Elevate/Blockers/Distros.pm
lib/Elevate/Blockers/EA4.pm
lib/Elevate/Blockers/Imunify.pm
lib/Elevate/Blockers/JetBackup.pm
lib/Elevate/Blockers/NICs.pm
lib/Elevate/Blockers/WHM.pm
lib/Elevate/Components/Base.pm
lib/Elevate/Components/Grub2.pm
lib/Elevate/Components/Kernel.pm
lib/Elevate/Components/PerlXS.pm
lib/Elevate/Components/UnconvertedModules.pm
lib/Elevate/OS.pm
lib/Elevate/OS/CentOS7.pm
lib/Elevate/OS/CloudLinux7.pm
lib/Elevate/Service.pm
script/elevate-cpanel.PL
t/blocker-Databases.t

Case RE-697:  This is a refactor to remove the
'upgrade_to_pretty_name()' sub from the main script and make it an Elevate::OS key instead.  Additionally, this change resolves RE-698 by removing a hard coded value for the OS we are upgrading from the service file that we provide.
Changelog: Make 'upgrade_to_pretty_name' an Elevate::OS key

Make 'upgrade_to_pretty_name' an Elevate::OS key

---

.github/workflows/openstack.yml
.github/workflows/openstack/reboot_watch

* reboot_watch refactored to quickly check entire log for regex before it begins tail watching.
* reboot stages refactored starting with the first one which was overloaded to start elevate and then watch for a reboot.  Now we start elevate and move to a seperate job to then watch for the reboot and handle things in a more predictable and stable manner.
* Final stage job refactored to explicitly state and act on stage 5.

RE-750: GitHub workflows are stealing jobs from one another.  Fix the Concurrency settings.

---

.github/workflows/openstack.yml

Should only add another 30 seconds or so of runtime with the artifacts moving about the stages.

RE-786: Quick verbiage and formatting fix missing from from RE-750

---

elevate-cpanel
lib/Elevate/OS/CloudLinux7.pm

Fix: Unable to elevate system while "cl7h" repository is active

---

elevate-cpanel
lib/Elevate/Roles/Run.pm
t/ssystem.t

RE-699: die() instead of `return 42` within _ssystem().

RE-699: Swap 'return 42' line to Carp::croak()

---

.github/workflows/openstack.yml
.github/workflows/testsuite.yml

Case RE-851: Only run OpenStack GitHub Action when TestSuite Completes
Previously each workflow would run at the same time.
Now unit tests in testsuite will need to complete
prior to OpenStack's workflow starting.
Changelog:

Case RE-851: Only run OpenStack GitHub Action when TestSuite Completes

---

elevate-cpanel
lib/Elevate/Components/Imunify.pm

Case RE-862: The Imunify products have the ability to auto update themselves which can trigger a lock file being in place that will prevent the Imunify installer(s) from executing.  This change makes it so that we check to see if the lock file exists and wait for the PID to complete before attempting to uninstall Imunify in the pre_distro_upgrade stage.
Changelog: Ensure Imunify upgrade is not executing before attempting to
uninstall it

Ensure Imunify upgrade is not executing before uninstalling it

---

.github/workflows/website.yml

Case RE-880: Make sure website workflow only runs on elevate/main
Changelog:

Make sure website workflow only runs on elevate/main

---

.github/workflows/openstack.yml
.github/workflows/openstack/reboot_watch
.github/workflows/openstack/ssh_retry

Case RE-889: Increase Efficiency of Openstack Workflow
- reboot_retry:
- Now has pkill ability to end tail watching tasks that cause race conditions.
- Now more aggresive in handling exit codes.
- Better DEBUG verbiage.
- PID tracking to detect if elevate-cpanel has ended.
- openstack workflow
- Additional section required for Final Reboot accuracy.
- Removal of some verbose output no longer needed.
Changelog:

Increase Efficiency of Openstack Workflow

---

elevate-cpanel
lib/Elevate/Components/AbsoluteSymlinks.pm
lib/Elevate/Components/Imunify.pm
lib/Elevate/Components/KernelCare.pm
lib/Elevate/Components/MySQL.pm
lib/Elevate/Components/NixStats.pm
lib/Elevate/Components/Repositories.pm
lib/Elevate/Components/RmMod.pm
lib/Elevate/Components/RpmDB.pm
lib/Elevate/Components/WPToolkit.pm
lib/Elevate/RPM.pm
lib/Elevate/StageFile.pm
script/elevate-cpanel.PL
t/components-ea4.t

Case RE-723:  As it turns out, File::Copy provides copy and cp that behave slightly different.  The copy and move subs use the umask provided by the running processes shell.  The cp and mv try to preserve permissions for the file that is being copied or moved.  As such, we should prefer cp and mv over copy and move from File::Copy.
Changelog: Use mv and cp from File::Copy instead of copy and move

Use mv and cp from File::Copy instead of copy and move

---

elevate-cpanel
lib/Elevate/Components.pm
lib/Elevate/Components/Acronis.pm
lib/Elevate/Components/Repositories.pm
lib/Elevate/Components/UnconvertedModules.pm
lib/Elevate/Constants.pm
script/elevate-cpanel.PL
t/components-Acronis.t
t/components-UnconvertedModules.t

Case RE-575:
For Acronis, we must remove the Acronis backup agent package before the distro upgrade and re-install it after the distro upgrade.
Changelog: Support running elevate on systems that have the
Acronis backup agent installed.

Support elevate for systems with Acronis backup agent

---

elevate-cpanel
lib/Elevate/Components/Repositories.pm

Case RE-812:
Customizations to /etc/yum.repos.d/epel.repo cause failures in the 4th stage of elevate. The customized repo file prevents AlmaLinux 8 version of the repo file from being installed.
Changelog: Fix elevate failures stemming from having a
customized epel.repo file.

Ensure the epel.repo file is "clean"

---

elevate-cpanel
lib/Elevate/Components.pm
lib/Elevate/Components/PackageDupes.pm
lib/Elevate/Constants.pm
lib/Elevate/RPM.pm
script/elevate-cpanel.PL
t/components-PackageDupes.t

Case RE-652: If there are duplicate packages in the RPM database, certain steps during the ELevate process, such as running `yum update`, will fail, halting the process.
In order to try to rectify this issue, use the distro-provided `package-cleanup --dupes` command to list inappropriate duplicate packages, sort packages of common name according to version and release, and carefully remove all but the penultimate package in each list from the RPM database.
If YUM is still not able to untangle the remaining packages, users may restore the unmodified RPM database from the backup create and resolve the issues manually before continuing the ELevate process.
Changelog: Attempt to resolve duplicate RPMs found prior to upgrade.
By submitting pull requests to this repo, I agree to the Contributor …

Attempt to resolve duplicate RPMs

---

elevate-cpanel
lib/Elevate/Components/MySQL.pm
t/components-MySQL.t

Case RE-782:
Use mysqlcheck to check the integrity of their databases. Block if errors are found.
Changelog: Verify integrity of databases before elevation.

Assure DB integrity before elevation

---

elevate-cpanel
lib/Elevate/PkgMgr.pm
lib/Elevate/PkgMgr/Base.pm
lib/Elevate/PkgMgr/YUM.pm

Case RE-934: In RE-252, a bug was introduced that resulted in the final dnf update spitting out help text instead of updating the system.  This change updates the command to be valid again so that the final update takes place.
Changelog: Ensure final dnf update is executed

Ensure final dnf update is executed

---

elevate-cpanel
lib/Elevate/Components.pm
lib/Elevate/Components/Softaculous.pm
script/elevate-cpanel.PL
t/components-Softaculous.t

Case RE-846: It was reported that the Softaculous plugin for cPanel was displaying blank pages after ELevate, and that a re-install of the plugin fixed this issue. That seems reasonable, so detect Softaculous and re-install if present.
Changelog: Re-install Softaculous after upgrade.

Re-install Softaculous after upgrade

---

elevate-cpanel
lib/Elevate/Components/PackageRestore.pm
t/components-PackageRestore.t

Case RE-952: This adds 'sys-snap' to the list of packages that the PackageRestore component handles.  It also now explicitely removes the packages as it was previously relying on leapp to implicitely remove them.
Changelog: Add 'sys-snap' to the list of packages that the
PackageRestore component handles

Add 'sys-snap' to the list of packages that PackageRestore handles

---

elevate-cpanel
lib/Elevate/Components/Repositories.pm

Case RE-964: This change adds a better guard in
'Elevate::Components::Repositories::_autofix_duplicate_repoids'. It also initializes '$self->{__duplicate_repoids} as a href instead of an aref.
Changelog: Avoid Perl error in 'Elevate::Components::Repositories'

Avoid Perl error in 'Elevate::Components::Repositories'

---

elevate-cpanel
lib/Elevate/Components/EA4.pm
lib/Elevate/OS/Ubuntu20.pm
t/components-ea4.t

Case RE-954: This change updates it so that we check against 'Ubuntu_22.04' instead of 'Ubuntu_20.04' for upgrades from u20->u22.  It also ignore the package 'ea-noop-u20' from the dropped packages list since this package is specific for u20.
Changelog:

Update the target OS for the EA4 blocker on Ubuntu 20 upgrades

---

.github/workflows/openstack/prune_openstack
.github/workflows/pruner.yml

Case RE-1000: The `Openstack Pruner` job is consistently failing
- Moved all ENV exports to workflow file for export
Changelog:

The `Openstack Pruner` job is consistently failing

---

.github/workflows/openstack/reboot_watch

Case RE-991: Make reboot_watch more tolerant for failures and have it fail earlier if the script is reporting that it failed
Changelog:

Update reboot_watch to allow for one retry in case elevate-cpanel fails

---

.github/workflows/testsuite.yml
t/00_load.t
t/cpanel-setup
t/cpanfile

We originally used a CentOS 7 container. But it cannot be used to run native GitHub Actions relying on `node20`.
With this change we bump the container to use a more modern Almalinux 8 flavor, which is used for running our unit tests.
Note that we preserve the e2e test using a self-hosted runner relying on C7 VMs.

Switch to Alma8 for testsuite

---

elevate-cpanel
lib/Elevate/Roles/Run.pm
t/ssystem.t

Case RE-996: This makes it so that we automatically retry package manager commands that fail on the first attempt.  The reason for this change is that there is a network element involved that can sometimes fail due to temporary mirror problems and the command can pass after waiting for a few seconds.
Changelog: Add auto retry for package manager based commands

Add auto retry for package manager based commands

---

elevate-cpanel
lib/Elevate/Components.pm
lib/Elevate/Components/Ufw.pm
script/elevate-cpanel.PL
t/components-Ufw.t

Case RE-943: When performing an elevation from u20->u22, we rely on the do-release-upgrade script to perform the OS upgrade.  do-release-upgrade will create a secondary SSH connection on port 1022 as a fallback mechanism in the event that the primary SSH connection is disrupted during the upgrade process. This change ensures that port 1022 is open before executing do-release-upgrade so that the fallback method will work if it is required during the upgrade.  It also ensures that port 1022 is closed once the upgrade is complete if it was closed before the upgrade started.
Changelog: Add component to manage port 1022 for ELevations that rely on
the do-release-upgrade script to perform the OS upgrade
By submitting pull requests to this repo, I agree to the Contributor License Agreement which …

Add component to manage port 1022 for do-release-upgrade

---

elevate-cpanel
script/elevate-cpanel.PL

Case RE-800: There was some language output by --help that is CentOS specific. Update to make the help text inclusive of Ubuntu.
Changelog: Update --help to be more Ubuntu friendly

Update --help to be more Ubuntu friendly

---

elevate-cpanel
lib/Elevate/Components/AbsoluteSymlinks.pm
lib/Elevate/Components/Distros.pm
lib/Elevate/Components/IsContainer.pm
lib/Elevate/Components/SSH.pm
script/elevate-cpanel.PL
t/components-Distros.t
t/components-IsContainer.t
t/components-SSH.t

Case RE-945:
Audited all the strings for RHEL specific language & updated to be inclusive for Ubuntu. (However, strings output by code that only runs on RHEL systems were not updated. Also, the --help output was not updated as that is to be addressed in another case.)
Changelog: Update strings to be language agnostic for Ubuntu

Update strings to be language agnostic for Ubuntu

---

elevate-cpanel
lib/Elevate/Components/BootKernel.pm
lib/Elevate/Components/Grub2ChecksWorkarounds.pm
lib/Elevate/Components/Grub2ControlTest.pm
lib/Elevate/Components/IsContainer.pm
lib/Elevate/Components/Leapp.pm
lib/Elevate/Components/NICs.pm
lib/Elevate/Components/Ufw.pm
lib/Elevate/Leapp.pm
script/elevate-cpanel.PL
t/components-BootKernel.t
t/components-Grub2ControlTest.t
t/components-Ufw.t
t/leapp_upgrade.t

During resolution of RE-670, it was discovered that PR #554, which changed `should_run_distro_upgrade` to `upgrade_distro_manually`, failed to account for the fact that this change of name inverts the sense of the logic. Since none of the users of this method embed it in a logically complicated way, and since there aren't too many users, modify the method and its users to restore correct semantics.

Un-invert logic of upgrade_distro_manually

---

.github/workflows/openstack-centos-7.yml
.github/workflows/openstack-cloudlinux-7.yml
.github/workflows/openstack-ubuntu-20.yml
.github/workflows/openstack/centos-7/main.tf
.github/workflows/openstack/centos-7/variables.tf
.github/workflows/openstack/cloudlinux-7/main.tf
.github/workflows/openstack/cloudlinux-7/variables.tf
.github/workflows/openstack/ubuntu-20.04/main.tf
.github/workflows/openstack/ubuntu-20.04/variables.tf
.github/workflows/testsuite.yml

Case RE-1001: Move GitHub Secrets into Variables that can be
Changelog:

RE-1001: Move GitHub Secrets into Variables that have no Secrecy need

---

elevate-cpanel
lib/Elevate/OS/Ubuntu20.pm
t/is_experimental.t

Case RE-1160: Remove experimental status for u20->u22 upgrades
Changelog: Remove experimental status for u20->u22 upgrades

Remove experimental status for u20->u22 upgrades

---

elevate-cpanel
lib/Elevate/Components/EA4.pm

Case RE-1179: Previously, we did not filter out dropped packages from the list of EA4 packages that had config files that needed restored. This could result in odd bugs where a file was put in place that should not have been.
Changelog: Do not restore config files for dropped packages

Do not restore config files for dropped packages
